global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "mongodb_exporter"

    static_configs:
      - targets:
          - "mongodb_exporter:9216"  # Replace with your exporter service name
        labels:
          role: "mongos"

    metrics_path: /metrics
    scheme: http
